name: Pulumi - CI
on:
  push:
    branches:
      - main
jobs: 
  update: 
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
      - id : checkout
      - uses: actions/checkout@v4

      - name: Install Node
      - id : install-node
      - uses: actions/setup-node@v4
      - with:
          node-version-file: package.json
      
      - name: Install Dependencies
      - id : install-deps
      - run: | 
          npm install
      
      - name: Configure aws
      - id : configure-aws
      - uses: aws-actions/configure-aws-credentials@v4
      - with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region:  ${{ secrets.AWS_REGION }}
      